# -*- coding: utf-8 -*-
"""netcdf_query_for_LLM_check.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1quNGHweZrHzCL_t_YPlPDD-vHo8x3jpJ
"""

!pip install netCDF4
import pandas as pd
import os
from datetime import datetime
from netCDF4 import Dataset
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

netcdf_file_base=f'/content/drive/MyDrive/UC2_Netcdf/schouts_2.nc'
netcdf_file_scenario=f'/content/drive/MyDrive/UC2_Netcdf/schouts_1.nc'
base_data=Dataset(netcdf_file_base)
scenaroi_data=Dataset(netcdf_file_scenario)

"""**Query :Show the shape and size of all the parameters in the base netcdf file**"""

var=[]
shape=[]

params=list(base_data.variables.keys())
for param in params:
  var.append(param)
  shape.append(base_data.variables[param][:].shape)

shape_table=pd.DataFrame({'Parameter':var,'Shape':shape})
shape_table

"""**Generate  Table for Base and scenario Netcdf file**"""

import xarray as xr
import pandas as pd

def generate_full_node_table(netcdf_path: str) -> pd.DataFrame:
    """
    Generate a complete node-based table from SCHISM NetCDF, including:
    - static node info
    - dynamic variables over time (hvel_x/y, wsh_x/y, tp, WWM, zcor, elev)
    Returns a long-format DataFrame.
    """
    ds = xr.open_dataset(netcdf_path)

    # Node coordinates and static variables
    lat = ds['SCHISM_hgrid_node_y'].values
    lon = ds['SCHISM_hgrid_node_x'].values
    depth = ds['depth'].values
    node_bottom_index = ds['node_bottom_index'].values

    time = ds['time'].values

    records = []

    for t_index, t_val in enumerate(time):
        # Loop over vertical layers (hvel_x/y, zcor)
        for layer in range(ds['hvel_x'].shape[2]):  # 2 layers
            df_layer = pd.DataFrame({
                'time': t_val,
                'lat': lat,
                'lon': lon,
                'layer': layer,
                'depth': depth,
                'node_bottom_index': node_bottom_index,
                'zcor': ds['zcor'].values[t_index, :, layer],
                'elev': ds['elev'].values[t_index, :],
                'hvel_x': ds['hvel_x'].values[t_index, :, layer],
                'hvel_y': ds['hvel_y'].values[t_index, :, layer],
                'wsh_x': ds['wsh_x'].values[t_index, :],
                'wsh_y': ds['wsh_y'].values[t_index, :],
                'tp': ds['tp'].values[t_index, :],
                'WWM_1': ds['WWM_1'].values[t_index, :],
                'WWM_3': ds['WWM_3'].values[t_index, :],
                'WWM_9': ds['WWM_9'].values[t_index, :]
            })
            records.append(df_layer)

    # Combine all time steps and layers
    full_df = pd.concat(records, ignore_index=True)


    ds.close()
    return full_df

import xarray as xr
import pandas as pd

def generate_full_node_table2(netcdf_path: str) -> pd.DataFrame:
    """
    Generate a complete node-based table from SCHISM NetCDF, including:
    - static node info
    - dynamic variables over time (hvel_x/y, wsh_x/y, tp, WWM, zcor, elev)
    Returns a long-format DataFrame.
    """
    ds = xr.open_dataset(netcdf_path)

    # Node coordinates and static variables
    lat = ds['SCHISM_hgrid_node_y'].values
    lon = ds['SCHISM_hgrid_node_x'].values
    depth = ds['depth'].values
    node_bottom_index = ds['node_bottom_index'].values

    time = ds['time'].values

    records = []

    for t_index, t_val in enumerate(time):
        # Loop over vertical layers (hvel_x/y, zcor)
        for layer in range(ds['hvel_x'].shape[2]):  # 2 layers
            df_layer = pd.DataFrame({
                'time': t_val,
                'lat': lat,
                'lon': lon,
                'layer': layer,
                'depth': depth,
                'node_bottom_index': node_bottom_index,
                'zcor': ds['zcor'].values[t_index, :, layer],
                'elev': ds['elev'].values[t_index, :],
                'hvel_x': ds['hvel_x'].values[t_index, :, layer],
                'hvel_y': ds['hvel_y'].values[t_index, :, layer],
                'wsh_x': ds['wsh_x'].values[t_index, :],
                'wsh_y': ds['wsh_y'].values[t_index, :],
                'tp': ds['tp'].values[t_index, :],
                'WWM_1': ds['WWM_1'].values[t_index, :],
                'WWM_3': ds['WWM_3'].values[t_index, :],
                'WWM_9': ds['WWM_9'].values[t_index, :]
            })
            records.append(df_layer)

    # Combine all time steps and layers
    full_df = pd.concat(records, ignore_index=True)
    full_df['time']=pd.to_datetime(full_df ['time'])
    full_df['year']=full_df ['time'].dt.year
    full_df['month']=full_df ['time'].dt.month
    full_df['day']=full_df ['time'].dt.day
    full_df['hour']=full_df ['time'].dt.hour
    full_df['am_pm_time']=full_df ['time'].dt.strftime("%I:%M %p")
    full_df['day_time'] = full_df ['am_pm_time'].apply(lambda v: v[0:2] + '-' + v[-2:])


    ds.close()
    return full_df

base_table=generate_full_node_table2(netcdf_file_base)
base_table

base_table.dtypes

scenario_table=generate_full_node_table2(netcdf_file_scenario)
scenario_table

"""**Average Water depth Query  (using depth column)**"""

depth_data=base_table.groupby(['lat','lon'],as_index=False)['depth'].mean()
depth_data

"""Query 2: Make a plot for water depth (depth column) for base netcdf file .Take the average water depth for each lat(SCHISM_hgrid_node_y) , lon (SCHISM_hgrid_node_x).Make a Summary Table and a plot

##additional - Shape file
"""

import geopandas as gpd   #for shape file
import matplotlib.pyplot as plt

# Ensure you use depth_data for both data and coordinates
gdf = gpd.GeoDataFrame(
    depth_data,
    geometry=gpd.points_from_xy(depth_data['lon'], depth_data['lat']),
    crs="EPSG:4326"   # WGS84 lat/lon
)

# Plot
fig, ax = plt.subplots(figsize=(10, 8))

gdf.plot(
    ax=ax,
    column='depth',      # color by depth
    cmap='viridis',      # color map
    markersize=5,
    legend=True
)

ax.set_title("Geospatial Plot of Points Colored by Depth", fontsize=14)
ax.set_xlabel("Longitude")
ax.set_ylabel("Latitude")

plt.show()

"""**Query 3 :Find out the min and max depth. Make a plot and a table**"""

depth_max=base_table[base_table['depth']==base_table['depth'].max()][['lat','lon','depth']].drop_duplicates()
depth_min=base_table[base_table['depth']==base_table['depth'].min()][['lat','lon','depth']].drop_duplicates()
depth_main_max=pd.concat([depth_max, depth_min], ignore_index=True)
depth_main_max

import geopandas as gpd
import matplotlib.pyplot as plt

# Create GeoDataFrame
gdf = gpd.GeoDataFrame(
    depth_main_max,
    geometry=gpd.points_from_xy(depth_main_max['lon'], depth_main_max['lat']),
    crs="EPSG:4326"
)

# Plot
fig, ax = plt.subplots(figsize=(6,5))

# Use different colors for max and min
colors = ['red' if d == gdf['depth'].max() else 'green' for d in gdf['depth']]

gdf.plot(
    ax=ax,
    color=colors,
    markersize=80,
)

# Annotate depth values below the points with 90-degree rotation
for x, y, depth in zip(gdf.geometry.x, gdf.geometry.y, gdf['depth']):
    ax.text(
        x,
        y - 0.01,  # vertical offset to place below
        f"{depth:.2f} m",
        fontsize=8,
        ha='center',
        va='top',
        rotation=90,  # rotate text
        weight='bold',
        color='black'
    )

ax.set_title("Max & Min Depth Points", fontsize=12)
ax.set_xlabel("Longitude")
ax.set_ylabel("Latitude")

plt.show()

"""**Query : Mxiumun wave velocity Map For scenario netcdf file  (wsh_x and wsh_y)schouts_1**"""





scenario_table['wave_velocity']=np.sqrt(scenario_table['wsh_x']**2+scenario_table['wsh_y']**2)
wave_vel=scenario_table.groupby(['lat','lon'],as_index=False)['wave_velocity'].max()
wave_vel

import geopandas as gpd   #for shape file
import matplotlib.pyplot as plt

# Ensure you use depth_data for both data and coordinates
gdf = gpd.GeoDataFrame(
    wave_vel,
    geometry=gpd.points_from_xy(wave_vel['lon'], wave_vel['lat']),
    crs="EPSG:4326"   # WGS84 lat/lon
)

# Plot
fig, ax = plt.subplots(figsize=(10, 8))

gdf.plot(
    ax=ax,
    column='wave_velocity',
    cmap='viridis',
    markersize=5,
    legend=True
)

ax.set_title("Maximum wave_velocity", fontsize=14)
ax.set_xlabel("Longitude")
ax.set_ylabel("Latitude")

plt.show()

"""**Query :Plot the diffrence in surface elevation (elev column )  between two netcdf files  (base (sch2) - scenario (sch1) )**"""

base_ele = base_table.groupby(['lat', 'lon'], as_index=False)['elev'].mean()
scenario_ele = scenario_table.groupby(['lat', 'lon'], as_index=False)['elev'].mean()

# Merge with suffixes
merge_elev_table = base_ele.merge(
    scenario_ele,
    on=['lat', 'lon'],
    how='inner',
    suffixes=('_base', '_scenario')
)

merge_elev_table['elev_diff']=merge_elev_table['elev_base']-merge_elev_table['elev_scenario']
final_table=merge_elev_table[['lat','lon','elev_diff']]

gdf = gpd.GeoDataFrame(
    final_table,
    geometry=gpd.points_from_xy(final_table['lon'], final_table['lat']),
    crs="EPSG:4326"
)

# Plot
fig, ax = plt.subplots(figsize=(10, 8))

gdf.plot(
    ax=ax,
    column='elev_diff',
    cmap='viridis',
    markersize=5,
    legend=True
)

ax.set_title("Elevation Difference", fontsize=14)
ax.set_xlabel("Longitude")
ax.set_ylabel("Latitude")

plt.show()

base_ele = base_table.groupby(['lat', 'lon'], as_index=False)['elev'].mean()

gdf = gpd.GeoDataFrame(
    base_ele,
    geometry=gpd.points_from_xy(base_ele['lon'], base_ele['lat']),
    crs="EPSG:4326"
)

# Plot
fig, ax = plt.subplots(figsize=(10, 8))

gdf.plot(
    ax=ax,
    column='elev',
    cmap='viridis',
    markersize=5,
    legend=True
)

ax.set_title("Elevation SCH2", fontsize=14)
ax.set_xlabel("Longitude")
ax.set_ylabel("Latitude")

plt.show()

"""**Query : For this point (40.699429 (lat) ,	-8.756169 (lon)) show the change of surface elevation (elev column)  value over the time for base netcdf file (sch2)**"""

base_table_filter=base_table[(base_table['lat'].between(40.699429 - 1e-6, 40.699429 + 1e-6)) &
    (base_table['lon'].between(-8.756169 - 1e-6, -8.756169 + 1e-6))][['time','elev','hour','day_time']].drop_duplicates()
base_table_filter

base_table_filter.plot(x='day_time',y='elev',figsize=(12,6))

"""**Query : Maximun tp value for base netcdf file**"""

base_table_fil=base_table[base_table['tp']==base_table['tp'].max()][['lat','lon','day_time','tp']].drop_duplicates()
base_table_fil

"""**Query :Find the locations where the wave orbital velocity (wsh_x and wsh_y) exceeds the average velocity.  -- for sch2 file**"""

base=base_table.copy()
base_table['wave_velocity']=np.sqrt(base_table['wsh_x']**2+scenario_table['wsh_y']**2)
wave_vel=scenario_table.groupby(['lat','lon'],as_index=False)['wave_velocity'].mean()
wave_vel_filter=wave_vel[wave_vel['wave_velocity']>wave_vel['wave_velocity'].mean()]
wave_vel_filter

gdf = gpd.GeoDataFrame(
    wave_vel_filter,
    geometry=gpd.points_from_xy(wave_vel_filter['lon'], wave_vel_filter['lat']),
    crs="EPSG:4326"
)

# Plot
fig, ax = plt.subplots(figsize=(10, 8))

gdf.plot(
    ax=ax,
    column='wave_velocity',
    cmap='viridis',
    markersize=5,
    legend=True
)

ax.set_title("Wave velocity SCH2", fontsize=14)
ax.set_xlabel("Longitude")
ax.set_ylabel("Latitude")

plt.show()

"""**Query :Find the locations (top 100) where the wave orbital velocity (wsh_x and wsh_y) exceeds the average velocity. -- for sch2 file**"""

base=base_table.copy()
base_table['wave_velocity']=np.sqrt(base_table['wsh_x']**2+scenario_table['wsh_y']**2)
wave_vel=scenario_table.groupby(['lat','lon'],as_index=False)['wave_velocity'].mean()
wave_vel_filter=wave_vel[wave_vel['wave_velocity']>wave_vel['wave_velocity'].mean()].sort_values(by='wave_velocity',ascending=False)
wave_vel_filter['rank']=wave_vel_filter['wave_velocity'].rank(method='dense',ascending=False)
wave_vel_filter=wave_vel_filter[wave_vel_filter['rank']<101]
filter=wave_vel_filter[['lat','lon','wave_velocity']]
filter

gdf = gpd.GeoDataFrame(
    filter,
    geometry=gpd.points_from_xy(filter['lon'], filter['lat']),
    crs="EPSG:4326"
)

# Plot
fig, ax = plt.subplots(figsize=(10, 6))

gdf.plot(
    ax=ax,
    column='wave_velocity',
    cmap='viridis',
    markersize=5,
    legend=True
)

ax.set_title("wave_velocity Top 100 points SCH2", fontsize=14)
ax.set_xlabel("Longitude")
ax.set_ylabel("Latitude")

plt.show()

"""Query:
 [elev column]
Calculate the average water elevation between 10:00 AM and 3:00 PM for every

Create a summary table showing the water elevation variation over time.

Perform a time-wise analysis of the water elevation data.
"""

base_table=generate_full_node_table2(netcdf_file_base)

#1
filter_data=base_table[(base_table['hour']>=10) & (base_table['hour']<=15) ]
filter_data_elev=filter_data.groupby(['lat','lon'],as_index=False)['elev'].mean()
filter_data_elev

gdf = gpd.GeoDataFrame(
    filter_data_elev,
    geometry=gpd.points_from_xy(filter_data_elev['lon'], filter_data_elev['lat']),
    crs="EPSG:4326"
)

# Plot
fig, ax = plt.subplots(figsize=(10, 6))

gdf.plot(
    ax=ax,
    column='elev',
    cmap='viridis',
    markersize=5,
    legend=True
)

ax.set_title("Elevation", fontsize=14)
ax.set_xlabel("Longitude")
ax.set_ylabel("Latitude")

plt.show()

#2
elev_summary=filter_data.pivot_table(index=['lat','lon'],columns=['day_time'],values='elev',aggfunc='mean')
elev_summary

#3 time wise
time_wise=filter_data.groupby('day_time')['elev'].mean()
time_wise

time_wise.plot()

"""Query:
[elev column]
Calculate the average water elevation between 10:00 AM and 3:00 PM for every point within the bounding box:

Latitude: 40.7 to 40.8

Longitude: -9.0 to -8.8


"""

# Filter bounding box
bbox_df = filter_data[
    (filter_data['lat'] >= 40.7) & (filter_data['lat'] <= 40.8) &
    (filter_data['lon'] >= -9.0) & (filter_data['lon'] <= -8.8)
]
bbox_df.head()

bbox_df_elev=bbox_df.groupby(['lat','lon'],as_index=False)['elev'].mean()
bbox_df_elev

gdf = gpd.GeoDataFrame(
    bbox_df_elev,
    geometry=gpd.points_from_xy(bbox_df_elev['lon'], bbox_df_elev['lat']),
    crs="EPSG:4326"
)

# Plot
fig, ax = plt.subplots(figsize=(10, 6))

gdf.plot(
    ax=ax,
    column='elev',
    cmap='viridis',
    markersize=5,
    legend=True
)

ax.set_title("Elevation", fontsize=14)
ax.set_xlabel("Longitude")
ax.set_ylabel("Latitude")

plt.show()

